language: java

before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

matrix:
  include:
      - env: JDK='Oracle JDK 11'
        jdk: oraclejdk11
      - env: JDK='OpenJDK 10'
        install: . ./install-jdk.sh -F 10 -L GPL

addons:
  postgresql: "9.5"

services:
  - postgresql

before_script:
  - psql -f $TRAVIS_BUILD_DIR/server/core/src/main/resources/create_schema.sql -U postgres

script:
  - mvn clean test
